# Generated by Django 5.0.6 on 2024-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
